var DichvuController = require('../controllers/dichvu.controller');
var express = require('express');
var router = express.Router();
router.get('/list', DichvuController.getListDV);
router.get('/add', DichvuController.getAddDV);
router.post('/add', DichvuController.postAddDV);
router.get('/edit:id', DichvuController.getEditDV);
router.post('/edit:id', DichvuController.postEditDV);
router.get('/delete:id', DichvuController.getDeleteDV);
router.post('/delete:id', DichvuController.postDeleteDV);
module.exports = router;